{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "mfLymc_1HRMB"
      },
      "outputs": [],
      "source": [
        "import streamlit as st\n",
        "import pandas as pd\n",
        "\n",
        "# Import processed dataframe and cosine similarity values\n",
        "from project_prep import df, cosine_sim\n",
        "\n",
        "\n",
        "# Page settings\n",
        "st.set_page_config(\n",
        "    page_title=\"Profile Recommendation System\",\n",
        "    page_icon=\"🤝\",\n",
        "    layout=\"wide\"\n",
        ")\n",
        "\n",
        "\n",
        "# Recommendation function\n",
        "def recommend_profiles(profile_name, top_n=5):\n",
        "\n",
        "    # Find selected person's index\n",
        "    profile_index = df[df[\"Name\"] == profile_name].index[0]\n",
        "\n",
        "    # Get cosine similarity scores\n",
        "    scores = list(enumerate(cosine_sim[profile_index]))\n",
        "\n",
        "    # Sort from highest score to lowest score\n",
        "    scores = sorted(\n",
        "        scores,\n",
        "        key=lambda x: x[1],\n",
        "        reverse=True\n",
        "    )\n",
        "\n",
        "    # Skip the selected person's own profile\n",
        "    scores = scores[1:top_n + 1]\n",
        "\n",
        "    recommendations = []\n",
        "\n",
        "    for index, score in scores:\n",
        "\n",
        "        profile = df.iloc[index].copy()\n",
        "\n",
        "        # Convert decimal score into percentage\n",
        "        profile[\"Compatibility Score\"] = round(score * 100, 2)\n",
        "\n",
        "        recommendations.append(profile)\n",
        "\n",
        "    return pd.DataFrame(recommendations)\n",
        "\n",
        "\n",
        "# Application title\n",
        "st.title(\"🤝 NLP Profile Recommendation System\")\n",
        "\n",
        "st.write(\n",
        "    \"\"\"\n",
        "    Select a profile to find the most compatible people based on\n",
        "    their skills, education, experience and interests.\n",
        "    \"\"\"\n",
        ")\n",
        "\n",
        "st.divider()\n",
        "\n",
        "\n",
        "# Profile selection\n",
        "selected_profile = st.selectbox(\n",
        "    \"Select a profile:\",\n",
        "    df[\"Name\"].unique()\n",
        ")\n",
        "\n",
        "\n",
        "# Number of recommendations\n",
        "top_n = st.slider(\n",
        "    \"How many recommendations do you want?\",\n",
        "    min_value=1,\n",
        "    max_value=10,\n",
        "    value=5\n",
        ")\n",
        "\n",
        "\n",
        "# Display selected profile\n",
        "st.subheader(\"Selected Profile\")\n",
        "\n",
        "selected_data = df[df[\"Name\"] == selected_profile]\n",
        "\n",
        "st.dataframe(\n",
        "    selected_data,\n",
        "    use_container_width=True,\n",
        "    hide_index=True\n",
        ")\n",
        "\n",
        "\n",
        "# Recommendation button\n",
        "if st.button(\"Recommend Profiles\", type=\"primary\"):\n",
        "\n",
        "    result = recommend_profiles(\n",
        "        selected_profile,\n",
        "        top_n\n",
        "    )\n",
        "\n",
        "    st.success(\n",
        "        f\"Top {top_n} compatible profiles for {selected_profile}\"\n",
        "    )\n",
        "\n",
        "    st.subheader(\"Recommended Profiles\")\n",
        "\n",
        "    # Hide combined text if it exists\n",
        "    display_columns = [\n",
        "        column for column in result.columns\n",
        "        if column != \"combined_text\"\n",
        "    ]\n",
        "\n",
        "    st.dataframe(\n",
        "        result[display_columns],\n",
        "        use_container_width=True,\n",
        "        hide_index=True\n",
        "    )"
      ]
    }
  ]
}