# -*- coding: utf-8 -*-
"""Project_Prep(Unlox).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LJsRhxxJ7RYrBkK5-tvWk5DDzYMrrxGO
"""

# WorkFlow
# 1. Create Profile data
# 2. Load it using Pandas
# 3. Clean the skills text
# 4.convert text into numbers using TF-IDF
# 5.Compare Profiles using Cosine Similarity
# 6.Recommend the best-matching profiles
# 7.Later, build a simpe Streamlit App

# Install the Libraries
#!pip install pandas scikit-learn

import pandas as pd

# Create a small dataset
# 10 Profiles .. in project we have to create 100 profiles minimum (ref linkedin)

data = {
    "Name":[
        "Rahul",
        "Priya",
        "Akshaya",
        "Riya",
        "Sruthi",
        "Amna",
        "Bilal",
        "Raman",
        "Salim",
        "Sky"
    ],
    "Skills":[
        "Python SQL Machine Learning",
        "Java Spring Boot Microservices",
        "Python Deep Learning NLP",
        "Excel Power BI Data Analysis",
        "Python Flask Machine Learning",
        "Java SQL Spring Boot",
        "Python NLP Data Science",
        "React Node.js MongoDB",
        "Excel Tableau Data Visualization",
        "Python Flask Deep Learning"

    ]
}

df = pd.DataFrame(data)
df.to_csv("profiles.csv",index=False)
print(df)

print(df.shape)

df.isnull().sum()

df.info()

print(df.describe())

# Convert then into lower case
df['Skills'] = df['Skills'].str.lower()
print(df)

# TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
skill_vectors = tfidf.fit_transform(df['Skills'])
print(skill_vectors.toarray())

tfidf_table = pd.DataFrame(skill_vectors.toarray(),columns=tfidf.get_feature_names_out())
print(tfidf_table)

# cosine-Similarity
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(skill_vectors)
print(similarity_matrix)

similarity_df= pd.DataFrame(similarity_matrix, columns=df["Name"], index=df["Name"])
print(similarity_df)

similarity_percentage = similarity_df*100
similarity_percentage.round(2)

selected_name = "Bilal"
scores = similarity_df.loc[selected_name]
scores = scores.drop(selected_name)
top_matches = scores.sort_values(ascending=False).head(3)
top_matches = top_matches*100
print(top_matches)

# Create the recommendation function
def recommended_profiles(person_name, number_of_matches=3):

  # check whetehr the person exists
  if person_name not in df["Name"].values:
    print(f"{person_name} not found in the dataset")
    return

  # Get the selected person's similarity Score
  scores = similarity_df.loc[person_name]

  # Drop the selected person's own profile from the list
  scores = scores.drop(person_name)

  #Sort and select the top matches
  top_matches = scores.sort_values(ascending=False).head(number_of_matches)
  top_matches = top_matches*100

  print(f"Top {number_of_matches} matches for {person_name}:")
  for name, score in top_matches.items():
    print(f"{name}: {score:.2f}%")

recommended_profiles("Bilal",5)

